name: hero_games_case
description: "Hero Games Case"

publish_to: "ketvolkan"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  get: ^4.6.5 # linux,macos,web,windows
  awesome_dialog: ^2.2.1
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.1.2
  flutter_svg: ^2.0.0+1
  intl: ^0.18.0
  flutter_keyboard_visibility: ^5.4.0
  flutter_feather_icons: ^2.0.0+1
  permission_handler: ^10.2.0
  dio: ^5.2.1+1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"
  change_app_package_name: ^1.1.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/png/
    - assets/png/flags/
    - assets/jpg/
    - assets/json/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/kanit.ttf
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/jpg/logo_with_bg.jpeg"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/jpg/logo_with_bg.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/jpg/logo_with_bg.jpeg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/jpg/logo_with_bg.jpeg"
