name: jsontranslator
description: Json translator
publish_to: "none"
version: 2.1.6

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  process_run: ^0.13.1
  translator: ^0.1.7
  yaml: ^3.1.2

dev_dependencies:
